name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust tests
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - uses: Swatinem/rust-cache@v2

      - name: install system deps
        run: sudo apt-get install libxkbcommon-dev libudev-dev

      - name: Run tests
        run: cargo test --workspace --all-features

  clippy:
    name: Clippy
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - uses: Swatinem/rust-cache@v2

      - name: install system deps
        run: sudo apt-get install libxkbcommon-dev libudev-dev

      - name: Run clippy
        run: cargo clippy --workspace --all-features

  fmt:
    name: Rustfmt
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update

      - name: Run rustfmt
        run: cargo fmt --all --check --verbose

  prettier:
    name: Prettier fmt
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prettier
        run: npx prettier --check .
